---
layout: post
title: 'Symfony2: обработка исключения 404'
date: 2015-08-19 12:11:31.000000000 +03:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- HowTo
tags:
- php
- symfony2
meta:
  _wpcom_is_markdown: '1'
  sharing_disabled: '1'
  _rest_api_published: '1'
  _rest_api_client_id: "-1"
  _publicize_job_id: '13876895676'
author:
  login: russianpenguin
  email: maksim.v.zubkov@gmail.com
  display_name: russianpenguin
  first_name: Maksim
  last_name: Zubkov
permalink: "/2015/08/19/symfony2-%d0%be%d0%b1%d1%80%d0%b0%d0%b1%d0%be%d1%82%d0%ba%d0%b0-%d0%b8%d1%81%d0%ba%d0%bb%d1%8e%d1%87%d0%b5%d0%bd%d0%b8%d1%8f-404/"
---
<p>Допустим, что нам нужно обработать исключение 404 и вместо стандартного ответа сервера (или шаблона ошибки ответить специфической страницей.</p>
<p>Как кастомизировать страницы подробно описано в <a href="http://symfony.com/doc/current/cookbook/controller/error_pages.html">официальной документации</a>.</p>
<p>Нас будет интересовать пункт работы с эвентом kernel.exception.</p>
<p>Можно посмотреть один из <a href="http://symfonybricks.com/en/brick/custom-exception-page-404-not-found-and-other-exceptions">примеров</a> его использования.</p>
<p>Наш кейс: если symfony не смог обработать роут, то управление передается своему обработчику.</p>
<p>[code lang="php"]namespace AppBundle\Listener;<br />
use Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent;<br />
use Symfony\Component\HttpFoundation\Response;<br />
use Symfony\Component\HttpKernel\Exception\HttpExceptionInterface;<br />
use Symfony\Bundle\FrameworkBundle\Templating\EngineInterface;<br />
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;</p>
<p>class ExceptionListener<br />
{<br />
    protected $templating;<br />
    protected $kernel;</p>
<p>    public function __construct(EngineInterface $templating, $kernel)<br />
    {<br />
        $this-&gt;templating = $templating;<br />
        $this-&gt;kernel = $kernel;<br />
    }</p>
<p>    public function onKernelException(GetResponseForExceptionEvent $event)<br />
    {<br />
        if ($event-&gt;getException() instanceof NotFoundHttpException) {<br />
            $response = new Response();<br />
            $response-&gt;setContent(&quot;Какие-то данные&quot;);<br />
            //$response-&gt;setStatusCode(200) работать не будет<br />
            $response-&gt;headers-&gt;set('X-Status-Code', 200);<br />
            $event-&gt;setResponse($response);<br />
        }<br />
    }<br />
}[/code]</p>
<p>В config.yml прописывем что-то вроде</p>
<p>[code]services:<br />
    kernel.listener.app_exception_listener:<br />
        class: AppBundle\Listener\ExceptionListener<br />
        arguments: [@templating, @kernel]<br />
        tags:<br />
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }[/code]</p>
<p>И обратите внимание, что переопределение статуса ответа в виде<br />
[code lang="php"]$response-&gt;setStatusCode(200)[/code]</p>
<p>работать не будет. Мы не сможем переопределить статус отвта на 2хх с помощью этого метода (на любой другой можно).</p>
<p>Для того, чтобы мы могли переопределить ответ 404 нужно использовать метод</p>
<p>[code lang="php"]$response-&gt;headers-&gt;set('X-Status-Code', 200);[/code]</p>
